---
title: "R Notebook"
output: html_notebook
---
# Load Libraries
```{r}
library(tidyverse)
library(plotly)
library(openintro) #state abb
library(dygraphs)
library(arules)
library(arulesViz)
library(DT)
```

# ALL STORES AND SEASONS

```{r}
trans = read.transactions('data/mba_test.csv', format = 'basket', sep=',')

class(trans)
summary(trans)
arules::itemFrequencyPlot(trans, topN = 10)

rules = apriori(trans, parameter = list(supp=0.5, conf=0.9, minlen=2, maxlen=2))
rules = rules[!is.redundant(rules)]
rules = sort(rules, by='confidence', decreasing = TRUE)

summary(rules)
inspect(head(sort(rules, by ="lift"),10))
inspect(head(sort(rules, by ="support"),10))
inspect(head(sort(rules, by ="confidence"),10))

library("RColorBrewer")
plot(rules,control=list(col=brewer.pal(11,"Spectral")),main="")

subrules2 <- head(sort(rules, by="lift"), 10)
plot(subrules2, method="graph",control=list(type="items",main=""),engine = "htmlwidget")
```




# GROCERY STORES
```{r}
trans_groc = read.transactions('data/mba_groc.csv', format = 'basket', sep=',')

class(trans_groc)
summary(trans_groc)
arules::itemFrequencyPlot(trans_groc, topN = 10)

rules_groc = apriori(trans_groc, parameter = list(supp=0.5, conf=0.9, minlen=2, maxlen=2))
rules_groc = rules_groc[!is.redundant(rules_groc)]
rules_groc = sort(rules_groc, by='confidence', decreasing = TRUE)
summary(rules_groc)
inspect(head(sort(rules_groc, by ="lift"),10))

subrules_groc <- head(sort(rules_groc, by="lift"), 10)
plot(subrules_groc, method="graph",control=list(type="items",main=""),engine = "htmlwidget")

```

```{r}
inspect(head(sort(rules_groc, by ="lift"),10))

```


# DRUG STORES
```{r}
trans_drug = read.transactions('data/mba_drug.csv', format = 'basket', sep=',')

class(trans_drug)
summary(trans_drug)
arules::itemFrequencyPlot(trans_drug, topN = 10)

rules_drug = apriori(trans_drug, parameter = list(supp=0.5, conf=0.9, minlen=2, maxlen=2))
rules_drug = sort(rules_drug, by='confidence', decreasing = TRUE)
rules_drug = rules_drug[!is.redundant(rules_drug)]
summary(rules_drug)
inspect(head(sort(rules_drug, by ="lift"),15))

subrules_drug <- head(sort(rules_drug, by="lift"), 10)
plot(subrules_drug, method="graph",control=list(type="items",main=""),engine = "htmlwidget")
```



# LIQUOR AND TOBACCO STORES
```{r}
trans_liq = read.transactions('data/mba_liq.csv', format = 'basket', sep=',')

class(trans_liq)
summary(trans_liq)
arules::itemFrequencyPlot(trans_liq, topN = 10)

rules_liq = apriori(trans_liq, parameter = list(supp=0.5, conf=0.9, minlen=2, maxlen=2))
rules_liq = sort(rules_liq, by='confidence', decreasing = TRUE)
rules_liq = rules_liq[!is.redundant(rules_liq)]
summary(rules_liq)
inspect(head(sort(rules_liq, by ="lift"),10))

subrules_liq <- head(sort(rules_liq, by="lift"), 10)
plot(subrules_liq, method="graph",control=list(type="items",main=""),engine = "htmlwidget")
```



# CONVENIENCE STORES

```{r}
trans_con = read.transactions('data/mba_con.csv', format = 'basket', sep=',')

class(trans_con)
summary(trans_con)
arules::itemFrequencyPlot(trans_con, topN = 10)

rules_con = apriori(trans_con, parameter = list(supp=0.5, conf=0.9, minlen=2, maxlen=2))
rules_con = sort(rules_con, by='confidence', decreasing = TRUE)
rules_con = rules_con[!is.redundant(rules_con)]
summary(rules_con)
inspect(head(sort(rules_con, by ="lift"),15))

subrules_con <- head(sort(rules_con, by="lift"), 10)
plot(subrules_con, method="graph",control=list(type="items",main=""),engine = "htmlwidget")

```



## SEASONS

# SPRING
```{r}
#trans_sp = read.transactions('data/mba_sp.csv', format = 'basket', sep=',')

class(trans_sp)
summary(trans_sp)
arules::itemFrequencyPlot(trans_sp, topN = 10)

rules_sp = apriori(trans_sp, parameter = list(supp=0.3, conf=0.9, minlen=2, maxlen=2))
rules_sp = sort(rules_sp, by='confidence', decreasing = TRUE)
rules_sp = rules_sp[!is.redundant(rules_sp)]
summary(rules_sp)
inspect(head(sort(rules_sp, by ="lift"),15))

subrules_sp <- head(sort(rules_sp, by="lift"), 10)
plot(subrules_sp, method="graph",control=list(type="items",main=""),engine = "htmlwidget")
```




# SUMMER
```{r}
#trans_su = read.transactions('data/mba_su.csv', format = 'basket', sep=',')

class(trans_su)
summary(trans_su)
arules::itemFrequencyPlot(trans_su, topN = 10)

rules_su = apriori(trans_su, parameter = list(supp=0.3, conf=0.9, minlen=2, maxlen=2))
rules_su = sort(rules_su, by='confidence', decreasing = TRUE)
rules_su = rules_su[!is.redundant(rules_su)]
summary(rules_su)
inspect(head(sort(rules_su, by ="lift"),15))

subrules_su <- head(sort(rules_su, by="lift"), 10)
plot(subrules_su, method="graph",control=list(type="items",main=""),engine = "htmlwidget")
```




# FALL
```{r}
#trans_fa = read.transactions('data/mba_fa.csv', format = 'basket', sep=',')

class(trans_fa)
summary(trans_fa)
arules::itemFrequencyPlot(trans_fa, topN = 10)

rules_fa = apriori(trans_fa, parameter = list(supp=0.3, conf=0.9, minlen=2, maxlen=2))
rules_fa = sort(rules_fa, by='confidence', decreasing = TRUE)
rules_fa = rules_fa[!is.redundant(rules_fa)]
summary(rules_fa)
inspect(head(sort(rules_fa, by ="lift"),15))

subrules_fa <- head(sort(rules_fa, by="lift"), 10)
plot(subrules_fa, method="graph",control=list(type="items",main=""),engine = "htmlwidget")
```


# WINTER
```{r}
#trans_wi = read.transactions('data/mba_wi.csv', format = 'basket', sep=',')

class(trans_wi)
summary(trans_wi)
arules::itemFrequencyPlot(trans_wi, topN = 10)

rules_wi = apriori(trans_wi, parameter = list(supp=0.3, conf=0.9, minlen=2, maxlen=2))
rules_wi = sort(rules_wi, by='confidence', decreasing = TRUE)
rules_wi = rules_wi[!is.redundant(rules_wi)]
summary(rules_wi)
inspect(head(sort(rules_wi, by ="lift"),15))

subrules_wi <- head(sort(rules_wi, by="lift"), 10)
plot(subrules_wi, method="graph",control=list(type="items",main=""),engine = "htmlwidget")
```



```{r}
library(VennDiagram)
```
```{r}
unlist(attributes(sort(arules::itemFrequency(trans_wi),decreasing=TRUE)[0:20]),use.names=FALSE)
```

# Venn Diagrams for store types and top frequent items
```{r}
drug = unlist(attributes(sort(arules::itemFrequency(trans_drug),decreasing=TRUE)[0:20]),use.names=FALSE)
groc = unlist(attributes(sort(arules::itemFrequency(trans_groc),decreasing=TRUE)[0:20]),use.names=FALSE)
liq = unlist(attributes(sort(arules::itemFrequency(trans_liq),decreasing=TRUE)[0:20]),use.names=FALSE)
con = unlist(attributes(sort(arules::itemFrequency(trans_con),decreasing=TRUE)[0:20]),use.names=FALSE)

require("gplots") 
venn(list(Supermarket = groc, 'Drug Store' = drug))
venn(list(Supermarket = groc, 'Liquor and Tobacco Store' = liq))
venn(list(Supermarket = groc, 'Convenience Store' = con))
venn(list('Convenience Store' = con, 'Drug Store' = drug))
venn(list('Convenience Store' = con, 'Liquor and Tobacco Store' = liq))
venn(list('Convenience Store' = con, Supermarket = groc))
#venn(list('Drug Store' = drug , 'Liquor and Tobacco Store' = liq))
#venn(list(Supermarket = groc, 'Drug Store' = drug, 'Liquor and Tobacco Store' = liq, 'Convenience Store' = con))

```




