---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(hrbrthemes)
```


```{r}
store_r = read.csv(file = 'data/store_r2.csv')

head(store_r)
```


```{r}
coeff <- .175

ggplot(data=store_r, aes(x=Year)) +
  
  geom_bar(aes(y=Percent, fill = Store.Type), stat = 'identity',size=.1) + 
  geom_line( aes(y=Volume.Sold_y), size=2, color="#000eff") +
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Liters Sold (Millions)",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~./coeff, name="Percent Volume Sold (Liters)")
  ) +
  scale_fill_discrete(name = "Store Type") +
  theme_ipsum() +

  theme(
    axis.title.y = element_text(color = "#000eff", size=13),
    axis.title.y.right = element_text(color = "#000000", size=13, hjust=-0.1),
    axis.title.x = element_text(size = 13, hjust = 0.5),
    axis.text.x = element_text(angle=-45)
  ) +

  ggtitle("Store Sale Trends")
```

need number of types of stores in stacked bar graph
```{r}
ggplot() +
  
  geom_bar(data=store_bar_p_y, aes(x=Year, y=Volume.Sold, fill = Store.Type), stat = 'identity',position = 'fill') 

```
```{r}
ggplot(data = store_line_vol_y , aes(x=Date, y=Volume.Sold)) +
  
  geom_line() 
```
```{r}

head(store_line_vol_y)
```

rename column to have _ and lowercase
columns store number to group by and count then the store type date